### ISSUE TITLE
Support plugging in your own OpenTelemetry exporter

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-auto-instr-java#8]
[as opposed to using an APM vendor's agent that wraps this project and embeds the vendor's exporter]

This is a bit tricky because the OpenTelemetry API and SDK that the agent use are shaded, so the exporter must be shaded as well to match.

There are (at least) two options for shading the user exporter:

* Provide a tool that end users can run to shade the OpenTelemetry exporter that they want to use
* Shade the OpenTelemetry exporter dynamically at runtime before loading it

**Comment by prydin** [comment]
What if we took the more painless route of using the native OpenTelemetry Collector protocol and have people use a collector "sidecar" to do the translation to the target protocol?

**Comment by jkwatson** [comment]
I think that allowing people to use OTel without a collector and sending to their vendor of choice is still very important. I'd hate to have to stand up a collector to do local development, for example.

**Comment by prydin** [comment]
I'm taking a stab at this. I'll implement some kind of prototype we can use as basis for further design. Please assign this to me!

**Comment by prydin** [comment]
I came up with a prototype design for this. Here are some of the considerations:

## Early or late shading?
The best spot to load custom exporters seems to be in the ```TracerInstaller``` class under ```agent_tooling```. Loading it in this context means that the OpenTelemetry API needs to be shaded. This can be done in three ways: At exporter build time, using some CLI tool on a vendor JAR or dynamically at runtime. Each approach has its pros and cons.

### Exporter build time
This involves adding a mandatory list of relocation statements to the gradle script that builds the exporter. Since the OpenTelemetry API is brought in as a ```compileOnly```, the only effect this would have is to change every reference to the API to a shaded one. 

#### Pros
* Easy to implement
* Requires no additional code 
* Requires no costly processing at agent load time

#### Cons
* Requires awareness of the auto agent from exporter developers (probably needed anyway, see below)
* Exporters will have to be recompiled with a new version of their gradle script if the auto agent ever changes its shading.

### CLI Tool
With this approach, we would provide a simple CLI tool that allows users to apply the required shading etc to any exporter JAR.

#### Pros
* Relieves exporter developers from having to deal with auto agent specifics.
* Requires no costly processing at agent load time

#### Cons
* Doubtful that it's possible to completely relieve the exporter developers from any awareness of the auto agent, since we need a way to specify bootstrapping etc.
* An additional tool to write and maintain

### Runtime shading
Here, shading would be done at exporter load time and the exporter could be made completely unaware of the auto agent (restrictions apply, see below).

#### Pros
* Relieves exporter developers from having to deal with auto agent specifics.
* Exporters won't break if we change the shading rules.
* No extra tools to run

#### Cons
* Doubtful that it's possible to completely relieve the exporter developers from any awareness of the auto agent, since we need a way to specify bootstrapping etc.
* Relatively difficult to implement
* ByteBuddy doesn't seem to have this type class transformation functionality out-of-the-box (I could be wrong here). ASM has it, but don't want to drag in another bytecode manipulation package.
* Processing could be quite costly and we're trying to reduce the load time.

## Current design

### Shared library
The exporter and the auto agent need to share a very small package in order to obtain a factory, share configuration etc. This is currently done through the ```exporter-support``` module in the auto agent. This should probably be moved to ```opentelemetry-java``` once we've nailed down the design.

The package contains two classes:
```ConfigProvider``` a simple interface with basic getters that allows the exporter to read arbitrary configurations from the agent. A ```DefaultConfigProvider``` implementation exists that provides configurations from the agent config.

```ExporterFactory``` interface that specifies the creation of a ```SpanExporter``` based on a ```ConfigProvider```. The exporter project must implement an instance of this and map the configuration to the programmatic way of creating an exporter.

### Bootstrapping
In order to be compatible, an exporter needs to provide two things (in addition to the factory described above).

* A Bootstrap class. This can be any class that implements a ```getFactory()``` method.
* A ```Ota-Bootstrap-Class``` proprety in the manifest that contains the fully qualified name of the bootstrap class.

The bootstrap procedure in the auto agent works as follows:
* Read the ```ota.exporter.jar``` property
* Create a ```URLClassLoader``` based on that property.
* Load the MANIFEST.MF and extract the ``Ota-Bootstrap-Class``` property.
* Using the newly created ClassLoader, try to load the class referred to by the manifest property.
* Using reflection, call the ```getFactory()``` method to get a factory.
* Construct a ```ConfigProvider```
* Call ```fromConfig()``` on the factory.
* Register the exporter with the tracer.

## Sample exporter
A sample exporter is available under the ```dummy-exporter``` module. It simply prints the spans to stdout. This exporter is needed for testing, but should probably be moved under an existing module.

Current code:
https://github.com/prydin/opentelemetry-auto-instr-java/tree/prydin-exporter-experiment

**Comment by jkwatson** [comment]
would the exporter-build-time option mean that non-auto-instrumentation users would have to deal with oddball packaging?

**Comment by prydin** [comment]
Good question! I think I would generate two separate jars. One standard jar with no weirdness and one that has the auto stuff in it. That's what I'm planning to do with the vendor specific one I'm working on now.

**Comment by prydin** [comment]
Of course, the special auto jar could be generated using a separate gradle task so it's not done by default, but the logic would be the same.

**Comment by jkwatson** [comment]
Cool. I looked at your dummy exporter. Seems like this is not a lot to ask of people who want their exporters to work auto-magically with the auto-instrumentation system. Would they also need to provide a standard configuration mechanism for their exporter?

**Comment by prydin** [comment]
All they have to do is to ready properties of their choice from the ConfigProvider they get passed. Then they can use builders or whatever they want to set it up. Like this:

```
public SpanExporter fromConfig(ConfigProvider config) {
    WavefrontSpanExporter.Builder b = WavefrontSpanExporter.Builder.newBuilder();
    String proxy = config.getString(PROXY, null);
    String url = config.getString(WAVEFRONT_URL, null);
    if (proxy != null) {
      if (url != null) {
        throw new IllegalArgumentException(
            "Settings " + PROXY + " and " + WAVEFRONT_URL + " are mutualy exclusive");
      }
      WavefrontSpanExporter.ProxyClientBuilder pb = b.proxyClient(proxy);
      pb.metricsPort(config.getInt(METRICSPORT, 2878));
      pb.tracingPort(config.getInt(TRACEPORT, 30000));
      pb.flushIntervalSeconds(config.getInt(FLUSH_INTERVAL, 5));
      return pb.build();
    } else if (url != null) {
      String token = config.getString(TOKEN, null);
      if (token == null) {
        throw new IllegalArgumentException(
            "Setting " + TOKEN + " must be specified for direct connections");
      }
      WavefrontSpanExporter.DirectClientBuilder db = b.directClient(url, token);
      db.flushIntervalSeconds(config.getInt(FLUSH_INTERVAL, 5));
      return db.build();
    } else {
      throw new IllegalArgumentException(
          "Either " + PROXY + " or " + WAVEFRONT_URL + " need to be specified");
    }
  }
```

The capability of configuring an exporter from some kind of config should, in my opinion, be inherent to opentelemetry-java at some point. But that's above my pay grade right now. :)

**Comment by jkwatson** [comment]
Hmm. It doesn't really make sense to have exporters have to depend on code in the auto-instrumentation project (ConfigProvider, etc). Can you make a proposal (issue) in the java project for having this ConfigProvider be a part of the SDK?

**Comment by prydin** [comment]
You're absolutely right! They should definitely be part of the SDK. I just had issues linking the auto instrumenter to an unreleased jar in my file system, so I resorted to this in order to produce a PoC. I forgot to mention that! Nothing should ever be dependent on the auto instrumenter in my opinion. It's a black box.

**Comment by prydin** [comment]
I will open an issue once we decide that this is the way forward. Let's discuss on the Thursday call!

**Comment by trask** [comment]
> Seems like this is not a lot to ask of people who want their exporters to work auto-magically with the auto-instrumentation system

This seems reasonable to me also.

One thought so far, can we use SPI / service loader instead to look up and instantiate the bootstrap class?

**Comment by prydin** [comment]
Doesn't a ```ServiceLoader``` require you to put a bunch of stuff in you META-INF? I wanted to make this configurable from system attributes and/or environment variables only.

**Comment by tylerbenson** [comment]
Instead of requiring shading at all, could the exporter be wrapped in an adapter/bridge at load time?

**Comment by prydin** [comment]
> Instead of requiring shading at all, could the exporter be wrapped in an adapter/bridge at load time?

Not sure I understand how that would work. Can you elaborate?

**Comment by trask** [comment]
Re: ServiceLoader, it would just be used for the Bootstrap Class discovery (replacing the `Ota-Bootstrap-Class` MANIFEST entry). It wouldn't affect the configuration proposal.

**Comment by prydin** [comment]
> Re: ServiceLoader, it would just be used for the Bootstrap Class discovery (replacing the `Ota-Bootstrap-Class` MANIFEST entry). It wouldn't affect the configuration proposal.

Hmmm... Yeah, that might actually work. Trying it out...

**Comment by prydin** [comment]
*hits head* I just realized that the ```ClassRemapper``` from ASM is available through ByteBuddy. OK, then the dynamic runtime shading thing isn't that hard to do I suppose.

**Comment by prydin** [comment]
Pushed code based on feedback from @trask, @tylerbenson and @jkwatson 

* Using the SPI pattern with ServiceLoader
* Implemented runtime shading

Have a peek at https://github.com/prydin/opentelemetry-auto-instr-java/tree/prydin-exporter-experiment of you like!

**Comment by trask** [comment]
This all sounds good to me. Can you submit a PR for more detailed review? Thx!

**Comment by tylerbenson** [comment]
It sounds like remapping at load time is the way to go.  Nice job.  One thing to consider... what happens if the exporter exists on a user's classloader and isn't on the system classpath (eg spring boot jar)?

**Comment by trask** [comment]
Initial implementation completed by #159 and #171
